### ISSUE TITLE
Support media input

### ISSUE THREAD

**Issue by Andmat7** [h5p/h5p-mark-the-words#25]
I want to prequalify a pull request related to the following:
User story:
As an developer I want to add media on the h5p-mark-the-words question, for example: use on language sites.
UX:
Not relevant
Technical solution:
add on scripts/mark-the-words.js this.setVideo and this.setImage functions, and add media config on semantics.json

**Comment by fnoks** [comment]
I think this is a good idea, it will make the content types more consistent! If you create a Pull Request, we will review it.
