### ISSUE TITLE
xAPI should be modelled as a multiple choice question

### ISSUE THREAD

**Issue by garemoko** [h5p/h5p-mark-the-words#7]
Mark the words is effectively a multiple choice question where each word in the sentence is an option. 

It should therefore be represented as a multiple choice question with each word in the sentence listed as an interaction component within the choices property.

**Comment by thomasmars** [comment]
Indeed, it has been implemented as this, but I can see that it is not fired together with the xAPI events.
I have made an issue for fixing it at: https://h5ptechnology.atlassian.net/browse/HFP-426

**Comment by tajakobsen** [comment]
@garemoko Can you confirm that the xapi payload is correct now?

**Comment by garemoko** [comment]
Wow, that was quick. Added to my to-do list to check. I assume I just update to the latest version of H5P in wordpress?

**Comment by tajakobsen** [comment]
No, it's not publicly available yet, only on Github. It will be released soonish, if you want to wait for a real release. I can give you "poke" here when it's ready.

**Comment by garemoko** [comment]
Ok. I'll keep this on the end of my to-do list and test if I get time, otherwise I'll test when the release is out since that's a lot easier to update.

**Comment by tajakobsen** [comment]
@garemoko! The new release is out now. :)

**Comment by garemoko** [comment]
@tajakobsen Looks good!
